//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections items count mismatch, the collections must have the same amount of items..
        /// </summary>
        internal static string Argument_CollectionsItemsCountMismatch {
            get {
                return ResourceManager.GetString("Argument_CollectionsItemsCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object is not of an integer type..
        /// </summary>
        internal static string Argument_InvalidIntegerObj {
            get {
                return ResourceManager.GetString("Argument_InvalidIntegerObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument type is not an integer type..
        /// </summary>
        internal static string Argument_InvalidIntegerType {
            get {
                return ResourceManager.GetString("Argument_InvalidIntegerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument type is not an integer type code..
        /// </summary>
        internal static string Argument_InvalidIntegerTypeCode {
            get {
                return ResourceManager.GetString("Argument_InvalidIntegerTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object is not of a numeric type..
        /// </summary>
        internal static string Argument_InvalidNumericObj {
            get {
                return ResourceManager.GetString("Argument_InvalidNumericObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument type is not a numeric type..
        /// </summary>
        internal static string Argument_InvalidNumericType {
            get {
                return ResourceManager.GetString("Argument_InvalidNumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument type is not a numeric type code..
        /// </summary>
        internal static string Argument_InvalidNumericTypeCode {
            get {
                return ResourceManager.GetString("Argument_InvalidNumericTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split size must be greater than 1..
        /// </summary>
        internal static string Argument_InvalidSplitSize {
            get {
                return ResourceManager.GetString("Argument_InvalidSplitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the value is invalid..
        /// </summary>
        internal static string Argument_InvalidValueType {
            get {
                return ResourceManager.GetString("Argument_InvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot null or empty..
        /// </summary>
        internal static string Argument_NullOrEmpty {
            get {
                return ResourceManager.GetString("Argument_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument index must be a non-negative number..
        /// </summary>
        internal static string Argument_OutOfRange_ArgIndex {
            get {
                return ResourceManager.GetString("Argument_OutOfRange_ArgIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count must be non-negative and start index and count were out of bounds of the collection..
        /// </summary>
        internal static string Argument_OutOfRange_Count {
            get {
                return ResourceManager.GetString("Argument_OutOfRange_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the collection. It must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string Argument_OutOfRange_Index {
            get {
                return ResourceManager.GetString("Argument_OutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the destination is too short. It must be equal or greater to the collection items count..
        /// </summary>
        internal static string Argument_OutOfRange_LengthTooShort {
            get {
                return ResourceManager.GetString("Argument_OutOfRange_LengthTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current position of the stream and count were out of bounds for the stream or count is greater than the number of bytes from the current position of the stream to the end of the stream..
        /// </summary>
        internal static string Argument_StreamPositionOutOfBounds {
            get {
                return ResourceManager.GetString("Argument_StreamPositionOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot null or whitespace..
        /// </summary>
        internal static string Argument_StringNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Argument_StringNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred in the disposal of one or more of the collection&apos;s object..
        /// </summary>
        internal static string DisposableCollection_DisposingError {
            get {
                return ResourceManager.GetString("DisposableCollection_DisposingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum has no values defined..
        /// </summary>
        internal static string InvalidOperation_EnumNoDefinedValues {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumNoDefinedValues", resourceCulture);
            }
        }
    }
}
